interface=wlan1
bridge=br0
driver=nl80211

country_code=CN


ssid=MT7981_WiFi6_5G
hw_mode=a

channel=36
ieee80211n=1
ieee80211ac=1
ieee80211ax=1

ieee80211w=1

ieee80211d=1
ieee80211h=1

he_oper_chwidth=2
he_oper_centr_freq_seg0_idx=50
#he_capab=[TX-STBC-2X1][RX-STBC-1][SHORT-GI-80]
ht_capab=[LDPC][HT40+][HT40-][GF][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][MAX-AMSDU-7935][SHORT-GI-160][SHORT-GI-80]



vht_oper_chwidth=2
vht_oper_centr_freq_seg0_idx=50


#ht_capab=[MAX-MPDU-11454][SHORT-GI-80][SHORT-GI-160]
vht_capab=[MAX-MPDU-11454][SHORT-GI-80][HT-VHT-40]

wmm_enabled=1

wpa=2
wpa_passphrase=12345678

wpa_key_mgmt=WPA-PSK

wpa_group_rekey=3600
wpa_pairwise=CCMP
rsn_pairwise=CCMP
