interface=wlan1
bridge=br0
driver=nl80211

ssid=MT7981_WiFi6_5G
hw_mode=a

channel=36
ieee80211n=1
ieee80211ac=1
ieee80211ax=1


vht_oper_chwidth=2
vht_oper_centr_freq_seg0_idx=50
#he_oper_chwidth=1
#he_oper_centr_freq_seg0_idx=42

#vht_oper_chwidth=2
#vht_oper_centr_freq_seg0_idx=50
#he_oper_chwidth=2



vht_capab=[MAX-MPDU-11454][SHORT-GI-80][SHORT-GI-160]
wpa=0
ieee80211w=1
wmm_enabled=1
