interface=wlan0
driver=nl80211
ssid=APNAME

hw_mode=g
channel=1

ieee80211n=1     # 开启 Wi-Fi 4 (HT)
ieee80211ac=1    # 开启 Wi-Fi 5 扩展
ieee80211ax=1    # 开启 Wi-Fi 6 (HE)

auth_algs=1
channel=1

#wpa: which WPA implementation to use
#1 - wpa only
#2 - wpa2 only
#3 - both
wpa=0
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
wpa_passphrase=12345678
macaddr_acl=0
ignore_broadcast_ssid=0
